# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decision.Decision')),
            ],
        ),
    ]
